# Generated by Django 4.2.6 on 2023-11-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying', models.CharField(max_length=20)),
                ('symbol', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('strike', models.FloatField(blank=True, null=True)),
                ('side', models.CharField(choices=[('S', 'Short'), ('L', 'Long')], help_text='Short or Long', max_length=1)),
                ('type', models.CharField(choices=[('C', 'Call'), ('P', 'Put'), ('S', 'Stock')], help_text='Stock or Option Type: Stock, Put, or Call', max_length=1)),
            ],
            options={
                'ordering': ['expiration_date'],
            },
        ),
    ]
