# Generated by Django 4.2.6 on 2023-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliomanager', '0002_portfolio_quantity_alter_portfolio_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='symbol',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
